export const REQUEST_API_TOKEN = 'REQUEST_API_TOKEN';
export const RECEIVE_API_TOKEN_SUCCESS = 'RECEIVE_API_SUCCESS';
export const RECEIVE_API_TOKEN_FAILURE = 'RECEIVE_API_FAILURE';
export const LOGIN_USER = 'LOGIN_USER';
export const DID_ANSWER = 'DID_ANSWER';
export const PERFORMANCE_USER = 'PERFORMANCE_USER';
export const GET_PROFILE_PICTURE = 'GET_PROFILE_PICTURE';
export const RESET_ANSWER = 'RESET_ANSWER';
