export const REQUEST_API_TOKEN = 'REQUEST_API_TOKEN';
export const RECEIVE_API_TOKEN_SUCCESS = 'RECEIVE_API_SUCCESS';
export const RECEIVE_API_TOKEN_FAILURE = 'RECEIVE_API_FAILURE';
export const LOGIN_USER = 'LOGIN_USER';
